spring:
  application:
    name: letv-mas-router-tvproxy
    index: ${SERVER_IP}:${SERVER_PORT}
  cloud:
    client:
      ipAddress: ${SERVER_IP}
    loadbalancer:
      retry:
        enabled: true
  profiles:
    include: manager,omp,config,zuul,trace,biz,db

server:
  port: ${SERVER_PORT}
  tomcat: 
    accept-count: 1000 
    max-threads: 1000
    max-connections: 1000

security:
  basic:
    # 启用基本身份认证
    enabled: false
  user:
    name: letvMasRouter
    password: admin20180806
    role: USER

management:
  security:
    enabled: false
# /info 显示全部git版控相关信息
#  info:
#    git:
#      mode: full

endpoints:
  refresh:
    enabled: true
    # 安全验证
    sensitive: false
  shutdown:
    # curl -d "" http://letvMasRouter:admin20180806@127.0.0.1:9000/shutdown
    enabled: true
    # 安全验证
    sensitive: true

# 自定义系统日志输出
logout:
  path: /letv/logs/mas/router
  level: ERROR
  capacity: 30GB
